export const sdlCallbackInit: (d: unknown) => void;
export const sdlLaunchMain: (lib: string, func: string, args: string[]) => number;
export const sdlKeyEvent: (scancode: number, type: number) => number;
export const sdlTextAppend: (str: string) => number;
export const sdlTextEditing: (str: string, loc: number, length: number) => number;
export const sdlDialogExecCallback: () => void;
export const sdlDialogClearSelection: () => void;
export const sdlDialogFileSelected: (path: string) => void;
export const sdlSendDialogStatus: (idx: number) => void;
